package com.gallery.sync.ui.help

import androidx.annotation.StringRes
import com.gallery.sync.R

/**
 * Every explanation a (?) button can open.
 *
 * GENERATED by `tools/guide/build_guide.py` from `tools/guide/content/`. Do not edit: change the
 * guide's source and rebuild, so the pop-up, the published guide and this list cannot disagree.
 *
 * [slug] is the anchor in both published pages, which is how "Read more" lands on the right entry.
 */
enum class HelpTopic(
    val slug: String,
    @param:StringRes val title: Int,
    @param:StringRes val body: Int
) {
    ALBUMS_PERMISSION("albums-permission", R.string.help_albums_permission_title, R.string.help_albums_permission_body),
    ALBUMS_FILTER("albums-filter", R.string.help_albums_filter_title, R.string.help_albums_filter_body),
    ALBUMS_TOTALS("albums-totals", R.string.help_albums_totals_title, R.string.help_albums_totals_body),
    ALBUMS_ALL_BACKED_UP("albums-all-backed-up", R.string.help_albums_all_backed_up_title, R.string.help_albums_all_backed_up_body),
    ALBUMS_OPTIMISED_LINE("albums-optimised-line", R.string.help_albums_optimised_line_title, R.string.help_albums_optimised_line_body),
    ALBUMS_ARCHIVE_LINES("albums-archive-lines", R.string.help_albums_archive_lines_title, R.string.help_albums_archive_lines_body),
    ALBUMS_RUN_CONTROLS("albums-run-controls", R.string.help_albums_run_controls_title, R.string.help_albums_run_controls_body),
    ALBUMS_STATUS_LINE("albums-status-line", R.string.help_albums_status_line_title, R.string.help_albums_status_line_body),
    ALBUMS_LIST("albums-list", R.string.help_albums_list_title, R.string.help_albums_list_body),
    ALBUM_DETAIL("album-detail", R.string.help_album_detail_title, R.string.help_album_detail_body),
    ALBUM_FILE_STATUS("album-file-status", R.string.help_album_file_status_title, R.string.help_album_file_status_body),
    ALBUM_MERGE_WARNING("album-merge-warning", R.string.help_album_merge_warning_title, R.string.help_album_merge_warning_body),
    DIALOG_ARCHIVE_CONFIRM("dialog-archive-confirm", R.string.help_dialog_archive_confirm_title, R.string.help_dialog_archive_confirm_body),
    RESTORE_HERO("restore-hero", R.string.help_restore_hero_title, R.string.help_restore_hero_body),
    RESTORE_MESSAGE_LINE("restore-message-line", R.string.help_restore_message_line_title, R.string.help_restore_message_line_body),
    RESTORE_SELECTED_SUMMARY("restore-selected-summary", R.string.help_restore_selected_summary_title, R.string.help_restore_selected_summary_body),
    RESTORE_BUTTONS("restore-buttons", R.string.help_restore_buttons_title, R.string.help_restore_buttons_body),
    RESTORE_FOLDERS_LIST("restore-folders-list", R.string.help_restore_folders_list_title, R.string.help_restore_folders_list_body),
    RESTORE_FILES_LIST("restore-files-list", R.string.help_restore_files_list_title, R.string.help_restore_files_list_body),
    RESTORE_ACTION_BAR("restore-action-bar", R.string.help_restore_action_bar_title, R.string.help_restore_action_bar_body),
    ARCHIVE_HERO("archive-hero", R.string.help_archive_hero_title, R.string.help_archive_hero_body),
    ARCHIVE_CHECK_BUTTON("archive-check-button", R.string.help_archive_check_button_title, R.string.help_archive_check_button_body),
    ARCHIVE_EMPTY("archive-empty", R.string.help_archive_empty_title, R.string.help_archive_empty_body),
    ARCHIVE_FILE_LIST("archive-file-list", R.string.help_archive_file_list_title, R.string.help_archive_file_list_body),
    ARCHIVE_PROMPT("archive-prompt", R.string.help_archive_prompt_title, R.string.help_archive_prompt_body),
    DIALOG_EXIT_WARNING("dialog-exit-warning", R.string.help_dialog_exit_warning_title, R.string.help_dialog_exit_warning_body),
    SETTINGS_SECTION_GENERAL("settings-section-general", R.string.help_settings_section_general_title, R.string.help_settings_section_general_body),
    SETTINGS_LANGUAGE("settings-language", R.string.help_settings_language_title, R.string.help_settings_language_body),
    SETTINGS_APPEARANCE("settings-appearance", R.string.help_settings_appearance_title, R.string.help_settings_appearance_body),
    SETTINGS_MOBILE_DATA("settings-mobile-data", R.string.help_settings_mobile_data_title, R.string.help_settings_mobile_data_body),
    SETTINGS_SECTION_BACKUP("settings-section-backup", R.string.help_settings_section_backup_title, R.string.help_settings_section_backup_body),
    SETTINGS_ACCOUNT("settings-account", R.string.help_settings_account_title, R.string.help_settings_account_body),
    SETTINGS_DESTINATION("settings-destination", R.string.help_settings_destination_title, R.string.help_settings_destination_body),
    DIALOG_DESTINATION("dialog-destination", R.string.help_dialog_destination_title, R.string.help_dialog_destination_body),
    DIALOG_FOLDER_PICKER("dialog-folder-picker", R.string.help_dialog_folder_picker_title, R.string.help_dialog_folder_picker_body),
    SETTINGS_SECTION_ALBUMS("settings-section-albums", R.string.help_settings_section_albums_title, R.string.help_settings_section_albums_body),
    SETTINGS_FOLDERS("settings-folders", R.string.help_settings_folders_title, R.string.help_settings_folders_body),
    SETTINGS_DELETION("settings-deletion", R.string.help_settings_deletion_title, R.string.help_settings_deletion_body),
    SETTINGS_DELETION_WAIT("settings-deletion-wait", R.string.help_settings_deletion_wait_title, R.string.help_settings_deletion_wait_body),
    SETTINGS_DELETION_REVIEW("settings-deletion-review", R.string.help_settings_deletion_review_title, R.string.help_settings_deletion_review_body),
    DIALOG_DELETION_CONFIRM("dialog-deletion-confirm", R.string.help_dialog_deletion_confirm_title, R.string.help_dialog_deletion_confirm_body),
    SETTINGS_DEFAULT_MODE("settings-default-mode", R.string.help_settings_default_mode_title, R.string.help_settings_default_mode_body),
    SETTINGS_SECTION_SYNC("settings-section-sync", R.string.help_settings_section_sync_title, R.string.help_settings_section_sync_body),
    SETTINGS_OPTIMISE_PHOTOS("settings-optimise-photos", R.string.help_settings_optimise_photos_title, R.string.help_settings_optimise_photos_body),
    SETTINGS_OPTIMISE_VIDEO("settings-optimise-video", R.string.help_settings_optimise_video_title, R.string.help_settings_optimise_video_body),
    SETTINGS_OPTIMISE_VIDEO_STATUS("settings-optimise-video-status", R.string.help_settings_optimise_video_status_title, R.string.help_settings_optimise_video_status_body),
    SETTINGS_OPTIMISE_MODE("settings-optimise-mode", R.string.help_settings_optimise_mode_title, R.string.help_settings_optimise_mode_body),
    SETTINGS_VIDEO_AGE("settings-video-age", R.string.help_settings_video_age_title, R.string.help_settings_video_age_body),
    SETTINGS_VIDEO_QUALITY("settings-video-quality", R.string.help_settings_video_quality_title, R.string.help_settings_video_quality_body),
    SETTINGS_OPTIMISE_STATUS("settings-optimise-status", R.string.help_settings_optimise_status_title, R.string.help_settings_optimise_status_body),
    SETTINGS_SECTION_RESTORE("settings-section-restore", R.string.help_settings_section_restore_title, R.string.help_settings_section_restore_body),
    SETTINGS_SHOW_EMPTY_FOLDERS("settings-show-empty-folders", R.string.help_settings_show_empty_folders_title, R.string.help_settings_show_empty_folders_body),
    SETTINGS_SECTION_ARCHIVE("settings-section-archive", R.string.help_settings_section_archive_title, R.string.help_settings_section_archive_body);
}
